services:
  - type: web
    name: filmoracle
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn redmovierec_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" # Or your specific domain
      - key: CLOUDINARY_URL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
