services:
  - type: web
    name: filmoracle
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn redmovierec_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: filmoracle-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: filmoracle-db
    databaseName: filmoracle
    user: filmoracle